const teamData = {
  "Kyle Burks": {
    title: "Kyle Burks",
    position: "Founder & Owner",
    smallText:
      "Kyle Burks is the Founder and Owner of STR Marketplace, LLC. Kyle founded the company in 2006 to create a safe and secure online marketplace for Personal Seat Licenses (PSLs). Today, STR Marketplace operates the world’s largest set of websites for seat location transfers. The company's marketplace products include Seat Licenses, Seat Location Rights (seat locations without contractual rights), RV/Camping Location Rights, Waiting List Numbers, and more. As Founder and Owner, Kyle is responsible for the strategic direction and leadership of STR Marketplace. Under Kyle's leadership, STR Marketplace has seen dramatic revenue growth each year since 2006. STR Marketplace now operates 24 marketplaces for 22 different partners across the NFL, MLB, NASCAR, NBA NHL and horse racing. Since 2006, STR Marketplace has processed over $300 Million worth of transfers across all of its marketplaces. ",
    bigText:
      "Kyle has been mentioned in publications such as ESPN.com, New York Times, Bloomberg, Sports Business Journal, and Sports Illustrated, as well as being interviewed on television for Fox Business and Forbes Sports Money as a lead expert in discussing PSLs and their effect on sports and business. Prior to starting STR Marketplace, Kyle worked as a financial derivatives consultant at Deloitte in Houston, TX. Kyle graduated Summa Cum Laude from the Mays Business School at Texas A&M University where he earned his BBA in Accounting and a Master of Science in Finance. Under Kyle's leadership, STR Marketplace has played an active role in the community. STR Marketplace is a sponsor of the American Heart Association’s Bear Bryant Coach of the Year awards banquet. Kyle and his wife Steffi, a successful fundraiser, have served the American Heart Association in several capacities in order to help raise awareness and funds to fight heart disease. Kyle currently resides in Kemah, TX with his wife Steffi and their children, Ryan, Logan and Sadie.",
  },
  "Preston Hill": {
    title: "Preston Hill",
    position: "President",
    smallText:
      "Preston Hill is President of STR Marketplace. Preston is responsible for overseeing all day-to-day operations of STR Marketplace, including partnership development, accounting, finance, marketplace operations and website development. During his tenure, STR Marketplace has seen dramatic growth. New partnerships, such as the Dallas Cowboys, Minnesota Vikings, Toronto Maple Leafs and Toronto Raptors have helped continue to solidify STR Marketplace’s position as the world’s largest provider of seat transfer marketplaces. In addition to new partnership development, Preston is responsible for playing a key leadership role that includes providing direction for new product development. In 2011, STR Marketplace launched the world's first cloud-based portal, called STR Connect, for teams and venues to manage their seat transfers.",
    bigText:
      "Preston brings over twenty years of professional and collegiate sports business experience to STR. Prior to joining STR Marketplace, Preston worked for the NFL’s Houston Texans. During his tenure with the Texans (2001-2009), he held several positions in ticketing and corporate development. While with the Texans, Preston had the opportunity to assist in opening Houston’s Reliant Stadium in 2002, as well as being a part of the Texans corporate development team that was responsible for generating over $30 Million per year in local revenue. Prior to joining the Texans, Preston served as the Director of Business Operations for the athletic department at the University of Texas at Dallas. Preston is a proud graduate of the University of Alabama, where he was a four-year letterman on the men’s track and field team. Preston earned a Master of Science in Sports Administration from Troy University, where he served as an assistant coach for the men’s and women’s conference champion track and field teams. Preston also earned a Master of Business Administration from the University of St. Thomas' Cameron School of Business in Houston. Preston is active in the community of Houston. He serves on the Athletics Advisory Council and the Marketing and Communications Committee for the University of St. Thomas. Preston also serves on the Executive Leadership Committee for the American Heart Association’s Bear Bryant Coach of the Year awards banquet, as well as serving as chair of the Silent Auction Committee. Preston resides in Houston, TX with his wife, Anne Marie, and their children, John Radford, Charles Preston and Anne Louise. ",
  },
  "Ray Adams": {
    title: "Ray Adams",
    position: "Vice President of Technology & Website Development",
    smallText:
      "Ray Adams is the Vice President of Website Development and Technology for STR Marketplace. As the Vice President of Website Development and Technology, Ray is responsible for the design, development and maintenance of all STR’s online marketplaces. In addition to his website development responsibilities, Ray is also responsible for STR Marketplace’s website infrastructure and customer database management.",
    bigText:
      "Ray joined STR Marketplace permanently at the end of 2010; however, he has been a constant presence for STR since 2006, having been the original architect of SeasonTicketRights.com and all of STR’s team-branded marketplaces while working as a consultant. Since joining STR on a full-time basis, Ray has quickly made his mark by redesigning the website infrastructure to ensure online stability and security for our customers. In addition, he continues to play a critical role in the development of new marketplace enhancements that allow STR to provide the best possible service to its customers and team clients. Prior to joining STR Marketplace, Ray globally provided technology solutions, products and services to organizations ranging from Fortune 500 companies to government institutions. His 20+ years of experience in IT included OEM software integration, software distribution, a startup software company, an ERP solution creator, web-based technology consultant, mapping solutions and advanced development of web-based content and transactional systems. Ray is active in the community as well. He and his wife support the Houston Arboretum & Nature Center (HANC) and other local conservatories to encourage the education of conservation and resource awareness to maintain and preserve our natural habitats surrounding us. After the Oklahoma City bombing in 1995, Ray’s service was recognized with a certificate of appreciation from the Oklahoma City Fire Department. In Ray's spare time, he enjoys playing classical guitar. Ray resides in Houston with his wife Liliana and their two daughters. ",
  },
  "Chelsey Stamps": {
    title: "Chelsey Stamps",
    position: "Director of Accounting",
    smallText:
      "Chelsey Stamps is the Director of Accounting for STR Marketplace. Chelsey is responsible for all marketplace accounting and manages STR Marketplace's banking relationships. Chelsey joined STR Marketplace in early 2011 and was promoted to her current position in 2014. She previously held the title of Marketplace Accounting Coordinator.",
    bigText:
      "Prior to joining STR Marketplace Chelsey developed her sales and service skills while working as a Box Office Associate for Houston's Toyota Center, home of the Houston Rockets. Chelsey earned her Bachelor of Arts from the University of Louisiana at Lafayette, where she was on the Dean's List, and her Executive MBA from Texas Women's University. She is also a member of Delta Sigma Theta Sorority Inc. Chelsey resides in Houston, TX.",
  },
  "Michael Brown": {
    title: "Michael Brown",
    position: "Director of Marketplace Operations",
    smallText:
      "Michael Brown is the Director of Marketplace Operations for STR Marketplace. Michael is responsible for overseeing the day-to-day operations of the 22 marketplaces operated by STR Marketplace. His responsibilities include supervising marketplace sales, customer service and marketplace coordinators.",
    bigText:
      "Michael joined STR in 2014 as a Marketplace Coordinator and was promoted to Director of Marketplace Operations in January 2018. Prior to joining the team at STR, Michael developed his sales and customer service skills in the hospitality and restaurant management field. Michael earned his Bachelor of Science from the University of Houston, where he was a Founding Father of the UH chapter of the Alpha Epsilon Pi Fraternity and a 4 year member of the Coog Crew. Michael is also active in the community. He has volunteered as Head Coach for the Team Houston Maccabi Boys 15-16 year old basketball team for the past four years, leading them to the gold medal in the 2018 JCC Maccabi Games in Los Angeles. Michael resides in Houston, TX.",
  },
  "Broderick Merritt": {
    title: "Broderick Merritt",
    position: "Chief Technology Officer",
    smallText:
      "Broderick Merritt, who often goes by Brody, is the Chief Technology Officer for STR Marketplace. As the CTO, he is responsible for STR’s overall technology strategy and implementation to continually innovate and enhance the customer, partner, and operational experience.",
    bigText:
      "Broderick brings over 10 years of experience working with PropTech, InsurTech, and FinTech in enterprise and SMB environments where he led initiatives globally in R&D, product development, architecture, integrations, data and strategy establishing transformative and innovative solutions for both B2C and B2B demands. A natural technology leader passionate about growing and transforming businesses through digital capabilities, Broderick brings a unique blend of technical prowess and business acumen that’s been instrumental in driving projects from ideation to nation-wide rollouts, mergers and acquisitions, and partnerships. As a lifelong technologist, Broderick has been coding and tinkering with software since childhood - fully embracing technology as a change enabler and gateway to the future in day-to-day life and next-gen business models. He’ll regularly follow emerging technologies and attend conferences to stay on top of trends for continuous learning. In volunteer time, he'll advocate and mentor high school computer science programs, be a guest speaker at conferences, assist local start-ups, and participate on university project presentation panels. Broderick resides in Houston, TX with his family.",
  },
};
